version: "3"
services:
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: localhost:5000/tony/splitunwise
    network_mode: host
    volumes:
      - type: bind
        source: ./src
        target: /src
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    network_mode: host
    environment:
      - POSTGRES_DB=split
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
